### ISSUE TITLE
Analytics Usage' is not submitted because of special characters like '&' and ',' in all exp_name

### ISSUE THREAD

**Issue by BalammaBoya** [openedx-vlead/open-edx-unit-operation-reaction-engg-and-process-control-lab-nitk#1]
Analytics Usage' is not submitted because of special characters like '&' and ',' in  all exp_name

**Comment by mrudhvika940** [comment]
Corrected the exp_id of all experiments. Analytics usage is now submitting.

**Comment by sravanthimodepu** [comment]
Closing the issue.
